In [1]:
import torch
import numpy as np

In [2]:
var1 = torch.tensor([1,2,3,4,5,6])
var1

tensor([1, 2, 3, 4, 5, 6])

In [3]:
var1[3]

tensor(4)

In [5]:
var1[-3:]

tensor([4, 5, 6])

In [6]:
var1.shape

torch.Size([6])

In [7]:
var1.view(3,2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [8]:
var1

tensor([1, 2, 3, 4, 5, 6])

In [9]:
var1.view(3,3)

RuntimeError: shape '[3, 3]' is invalid for input of size 6

## Vectors

In [11]:
import matplotlib.pyplot as plt

In [12]:
x = torch.tensor([1,2,3,4])
y = torch.tensor([5,6,7,8])

In [13]:
x + y

tensor([ 6,  8, 10, 12])

In [14]:
x*y

tensor([ 5, 12, 21, 32])

In [15]:
torch.dot(x,y)

tensor(70)

In [16]:
torch.dot(x,y.T)

tensor(70)

In [17]:
torch.dot(x.T,y)

tensor(70)

In [18]:
torch.matmul(x,y)

tensor(70)

In [19]:
torch.matmul(x.T,y)

tensor(70)

In [20]:
torch.matmul(x,y.T)

tensor(70)

## 2 dimensional (tensor of matrix)

In [23]:
x = torch.arange(1,21)

In [24]:
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20])

In [25]:
x = x.view(4,5)

In [26]:
x

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])

In [27]:
x[7:10]

tensor([], size=(0, 5), dtype=torch.int64)

In [28]:
x[1, 1:5]

tensor([ 7,  8,  9, 10])

## Matrix Multiplication

In [29]:
mat_a = torch.tensor([0, 3, 5, 5, 5, 2]).view(2, 3)
mat_b = torch.tensor([3, 4, 3, -2, 4, -2]).view(3, 2)

In [30]:
torch.matmul(mat_a,mat_b)

tensor([[ 29, -16],
        [ 38,   6]])

In [31]:
mat_a@mat_b

tensor([[ 29, -16],
        [ 38,   6]])

## Gradient

In [32]:
x = torch.tensor(2.0, requires_grad=True)
y = 3*x**2 + 5*x + 6

y.backward()
x.grad

tensor(17.)

In [35]:
a = torch.tensor(4.0, requires_grad=True)
b = torch.tensor(3.0, requires_grad=True)
c = torch.tensor(3.0, requires_grad=True)
y = 3*a**2 + 4*b**3 + 5*c

y.backward()
a.grad



tensor(24.)

In [36]:
c.grad

tensor(5.)