In [2]:
import torch
import numpy as np
from torch.nn import Linear
import torch.nn as nn

In [3]:
input_numb = 5
neuron_numb = 1 #output 
model = Linear(input_numb, neuron_numb)

In [4]:
print(model.weight, model.bias)

Parameter containing:
tensor([[-0.1812,  0.4110,  0.3486,  0.3787,  0.0667]], requires_grad=True) Parameter containing:
tensor([0.1714], requires_grad=True)


In [5]:
a = torch.tensor([1.0,2.0,3.0,4.0,5.0])

In [6]:
model(a)

tensor([3.7063], grad_fn=<AddBackward0>)

## Deep Neural Networks

In [9]:
class LR(nn.Module):
    def __init__(self,input_size,output_size):
        super().__init__()
        self.linear = nn.Linear(input_size, output_size) # linear is a layer.
    
    def forward(self, x):
        pred = self.linear(x)
        return pred
        
        

In [10]:
model = LR(1,1)

In [11]:
print(list(model.parameters()))

[Parameter containing:
tensor([[-0.1133]], requires_grad=True), Parameter containing:
tensor([-0.8989], requires_grad=True)]


In [12]:
x = torch.tensor([0.1])
model.forward(x)

tensor([-0.9102], grad_fn=<AddBackward0>)